services:
  api:
    container_name: api
    build: ./backend
    restart: unless-stopped
    networks:
      - express
    ports:
      - 3000
  front:
    container_name: app
    build: ./frontend
    environment:
      - ORIGIN=https://secure-web-dev-backend.onrender.com
    restart: unless-stopped
    networks:
      - express
    ports:
      - 3000:3000
    depends_on:
      - api

networks:
  express:
    driver: bridge
